#!/usr/bin/env python3
"""
Patch: Add domain-aware tool detection — inject only relevant tool patterns.

Modifies ToolWorker._detect_tool() to filter TOOL_DETECTION by domain,
using a TOOL_DOMAIN_MAP that maps each detection keyword to its domain.
When a domain_hint is provided (from Intent Parser), only tools matching
that domain are scored — this reduces pattern matching from ~130 to ~20
per query and avoids injecting irrelevant tool descriptions into context.
"""
from __future__ import annotations

from typing import Dict, List, Set

# ── Domain map: each TOOL_DETECTION keyword → its domain(s) ────────────
# This maps the keys used in TOOL_DETECTION (tool_worker.py) to domains.
# Domains match those used in captn/runtime/intent_parser.py.
TOOL_DOMAIN_MAP: Dict[str, str] = {
    # ── Coding ──
    "review": "coding",
    "code review": "coding",
    "code_review": "coding",
    "lint": "coding",
    "linter": "coding",
    "linting": "coding",
    "ruff": "coding",
    "mypy": "coding",
    "pylint": "coding",
    "flake8": "coding",
    "bandit": "coding",
    "format code": "coding",
    "code format": "coding",
    "format": "coding",
    "formatting": "coding",
    "security audit": "coding",
    "security": "coding",
    "type check": "coding",
    "type checking": "coding",
    "code quality": "coding",
    "code analysis": "coding",
    "code style": "coding",
    "check code": "coding",
    "analyse code": "coding",
    "analyze code": "coding",
    "code metrics": "coding",
    "check file": "coding",
    "loc": "coding",
    "cyclomatic": "coding",
    "complexity": "coding",
    "regex": "coding",
    "identify type": "coding",
    "type of": "coding",
    "dead code": "coding",
    "deadcode": "coding",
    "dependency graph": "coding",
    "dependencies": "coding",
    "codebase map": "coding",
    "map codebase": "coding",
    "project map": "coding",
    "health check": "coding",
    "project health": "coding",
    "code health": "coding",
    "engineering": "coding",
    # ── Math ──
    "simplify": "math",
    "expand": "math",
    "derivative": "math",
    "derive": "math",
    "differentiate": "math",
    "evaluate": "math",
    "solve": "math",
    "factor": "math",
    "equation": "math",
    "expression": "math",
    "gcd": "math",
    "lcm": "math",
    "prime": "math",
    "fibonacci": "math",
    "factorial": "math",
    "quadratic": "math",
    "mean": "math",
    "median": "math",
    "variance": "math",
    "stddev": "math",
    "trig": "math",
    "sine": "math",
    "cosine": "math",
    "tangent": "math",
    "sin": "math",
    "cos": "math",
    "logarithm": "math",
    "log": "math",
    "exponent": "math",
    "exp": "math",
    "absolute": "math",
    "permutation": "math",
    "binomial": "math",
    "distance": "math",
    "midpoint": "math",
    "bayes": "math",
    "probability": "math",
    "integrate": "math",
    "integral": "math",
    "taylor": "math",
    "taylor series": "math",
    "limit": "math",
    "solve system": "math",
    "linear system": "math",
    "matrix": "math",
    "determinant": "math",
    "matrix inverse": "math",
    "eigenvalue": "math",
    "interpolation": "math",
    "interpolate": "math",
    "statistics": "math",
    "natural language equation": "math",
    "nl to equation": "math",
    "convert to equation": "math",
    # ── Physics ──
    "force": "physics",
    "ohms law": "physics",
    "ohm": "physics",
    "kinematics": "physics",
    "kinetic energy": "physics",
    "potential energy": "physics",
    "momentum": "physics",
    "wave speed": "physics",
    "wavelength": "physics",
    "density": "physics",
    "ideal gas": "physics",
    "gas law": "physics",
    "work": "physics",
    "power": "physics",
    "pressure": "physics",
    "coulomb": "physics",
    "specific heat": "physics",
    "heat capacity": "physics",
    "kepler": "physics",
    "free fall": "physics",
    "projectile": "physics",
    # ── Chemistry ──
    "molar mass": "chemistry",
    "ph": "chemistry",
    "dilution": "chemistry",
    "mole": "chemistry",
    "concentration": "chemistry",
    "yield": "chemistry",
    "equilibrium": "chemistry",
    "enthalpy": "chemistry",
    "entropy": "chemistry",
    "gibbs": "chemistry",
    "balance": "chemistry",
    "arrhenius": "chemistry",
    "nernst": "chemistry",
    "half life": "chemistry",
    "half-life": "chemistry",
    "reaction rate": "chemistry",
    "chemical formula": "chemistry",
    "biology": "chemistry",
    # ── Philosophy / Logic ──
    "syllogism": "philosophy",
    "fallacy": "philosophy",
    "ambiguity": "philosophy",
    "argument": "philosophy",
    "epistemology": "philosophy",
    # ── Data / Text ──
    "finance": "data",
    "data science": "data",
    "utility": "general",
    # ── General / Fallback ──
    "ohmic": "physics",
    "check idempotency": "coding",
    "check security": "coding",
    "detect type": "coding",
    "detect div/0": "coding",
    "detect recursion": "coding",
    "validate binary": "coding",
    "validate kadane": "coding",
    "generate tests": "coding",
    "palindrome": "coding",
    "analyze nesting": "coding",
    "nesting depth": "coding",
}

# Domains and their associated keywords for reverse lookup
DOMAIN_KEYWORDS: Dict[str, Set[str]] = {}
for keyword, domain in TOOL_DOMAIN_MAP.items():
    DOMAIN_KEYWORDS.setdefault(domain, set()).add(keyword)

# Domain-to-tool-count for observability
DOMAIN_TOOL_COUNTS: Dict[str, int] = {}
for _, t_list in TOOL_DOMAIN_MAP.items():
    DOMAIN_TOOL_COUNTS[t_list] = DOMAIN_TOOL_COUNTS.get(t_list, 0) + 1